create table USER_TABLE
(
    ID int generated always as identity,
    NAME nvarchar2(30) not null,
    SURNAME nvarchar2(30) not null,
    FATHERNAME nvarchar2(30),
    EMAIL      nvarchar2(30) not null,
    SEX nchar
        constraint SEX_CHECK
            check ( SEX in ('m', 'f')),
    BIRTHDAY date,
    PASSWORD raw(16) not null,
    constraint USER_PK primary key(ID)
);
/
create table TOKENS
(
	ID int generated by default as identity
		constraint TOKENS_PK
			primary key,
	USERID int not null
	    constraint TOKENS_USER_TABLE_FK
			references USER_TABLE (ID)
				on delete cascade,
	TOKEN RAW(16) not null
)
/
create table DOC_TYPE
(
	ID int generated as identity
		constraint DOC_TYPE_PK
			primary key,
	TITLE nvarchar2(50) not null,
	REGEX nvarchar2(50) not null
)
/
create table PASSENGER
(
    ID int generated always as identity
        constraint PASSENGER_PK
            primary key ,
    USERID int not null
        constraint PASSENGER_USER_TABLE_FK
            references USER_TABLE(ID)
                on delete cascade,
    NAME nvarchar2(50) not null,
    SURNAME nvarchar2(50) not null,
    FATHERNAME nvarchar2(50),
    SEX nchar
        constraint PASSENGER_SEX_CHECK
            check ( SEX in ('m', 'f')),
    BIRTHDAY date not null ,
    PHONENUMBER nvarchar2(20),
    DOCTYPE int not null
        constraint PASSENGER_DOC_TYPE_FK
            references DOC_TYPE(ID),
    DOCNUM nvarchar2(50) not null
)
/
create table ORDER_STATUS(
    ID int generated always as identity
        constraint ORDER_STATUS_PK
            primary key,
    STATUS_NAME nvarchar2(50) not null,
    STATUS_DESCRIPTION nvarchar2(100) not null
)
/
create table ORDER_TABLE(
    ID raw(16)
        constraint ORDER_TABLE_PK
            primary key,
    USERID int not null
        constraint ORDER_TABLE_USER_TABLE_FK
            references USER_TABLE(ID),
    ORDERDATE date not null,
    STATUS int not null
        constraint ORDER_TABLE_ORDER_STATUS_FK
            references ORDER_STATUS(ID)
)
/

create table DESTPOINT(
    ID int generated as identity
        constraint DESTPOINT_PK
            primary key,
    NAME nvarchar2(30) not null,
    DESCRIPTION nvarchar2(100) not null
)
/

create table TRAIN_TYPE(
    ID int generated always as identity
        constraint TRAIN_TYPE_PK
            primary key,
    DESCRIPTION nvarchar2(100) not null
)
/
create table ROUTE(
    ID int generated by default as identity
        constraint ROUTE_PK
            primary key,
    ADDITIONAL_INFO nvarchar2(100)
)
/
create table TRAIN(
    ID int generated as identity
        constraint TRAIN_PK
            primary key,
    "NUMBER" decimal(5, 0),
    TRAIN_TYPE int not null
        constraint TRAIN_TRAIN_TYPE
            references TRAIN_TYPE(ID),
    ROUTE int not null
        constraint TRAIN_ROUTE_FK
            references ROUTE(ID)
)
/
create table DS_LINKS(
    ID int generated as identity
        constraint DS_LINKS_PK
            primary key,
    ROUTE int not null
        constraint DS_LINKS_ROUTE
            references ROUTE(ID)
                on delete set null,
    NEXT int
        constraint DS_LINKS_INNER_FK
            references DS_LINKS(ID)
                on delete set null,
    DESTPOINT int
        constraint DS_LINKS_DESTPOINT_FK
            references DESTPOINT(ID),
    COST decimal(5, 2) not null
)
/
alter table DS_LINKS add TIMEMINUT int;
/
create table TICKET(
    ID raw(16) not null
        constraint TICKET_PK
            primary key,
    ORDERID raw(16) not null
        constraint TICKET_ORDER_TABLE_FK
            references ORDER_TABLE(ID)
                on delete set null,
    TRAIN int not null
        constraint TICKET_TRAIN_FK
            references TRAIN(ID)
                on delete set null,
    "FROM" int not null
        constraint TICKET_DESTPOINT_FROM_FK
            references DESTPOINT(ID),
    "TO" int not null
        constraint TICKET_DESTPOINT_TO_FK
            references DESTPOINT(ID),
    COST decimal(5, 2) not null,
    CARIGENUM decimal(2, 0),
    SEATNUM decimal(3, 0)
)
/
alter table TICKET add PASSENGER int
    constraint TICKET_PASSENGER_FK
        references PASSENGER(ID);
/
create table FAVORITE_TRAIN(
    ID int generated as identity
        constraint FAVORITE_TRAIN_PK
            primary key,
    USERID int
        constraint FAVORITE_TRAIN_USER_TABLE_FK
            references USER_TABLE(ID)
                on delete cascade,
    TRAINID int
        constraint FAVORITE_TRAIN_TRAIN_FK
            references TRAIN(ID)
)
/
create table FAVORITE_PATH(
    ID int generated as identity
        constraint FAVORITE_PATH_PK
            primary key,
    USERID int
        constraint FAVORITE_PATH_USER_TABLE_FK
            references USER_TABLE(ID)
                on delete cascade,
    "FORM" int not null
        constraint FAVORITE_PATH_DESTPOINT_TO
            references DESTPOINT(ID),
    "TO" int not null
        constraint FAVORITE_PATH_DESTPOINT_FROM
            references DESTPOINT(ID)
)
/
create table NOTIFICATION(
    ID int generated as identity
        constraint NOTIFICATIONS_PK
            primary key,
    MESSAGE nvarchar2(500) not null,
    START_DATE DATE not null,
    END_DATE DATE not null
)
/
create table ONLINE_TABLE(
    ID int generated as identity
        constraint ONLINE_TABLE_PK
            primary key,
    DESTPOINT int
        constraint DESTPOINT_ONLINE_TABLE_FK
        references DESTPOINT(ID),
    TRAIN int
        constraint ONLINE_TABLE_TRAIN_FK
            references TRAIN(ID),
    ARRIVE date,
    DEPART date
)
/
commit;
/
create index TOKENS_TOKEN
    on TOKENS(TOKEN, USERID);
/
create index PASSENGER_USERID
    on PASSENGER(USERID);
/
create index TICKET_USERID
    on TICKET(ORDERID);
/